[alembic]
script_location = alembic
prepend_sys_path = .

[loggers]
keys = root

[handlers]
keys = console

[formatters]
keys = default

[logger_root]
level = WARN
handlers = console
qualname =

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = default

[formatter_default]
format = %(levelname)-5.5s [%(name)s] %(message)s
